services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml

  ollama-chat:
    image: ollama/ollama:latest
    container_name: ollama-chat
    ports:
      - "11434:11434"
    volumes:
      - ollama-chat:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
  kowalski-redis:
    image: redis:latest
    container_name: kowalski-redis
    ports:
      - "6379:6379"

volumes:
  ollama-chat:
